# Generated by Django 3.2.7 on 2021-09-09 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_medicine', models.CharField(max_length=255)),
                ('price_medicine', models.FloatField(blank=True)),
                ('use_medicine', models.TextField(blank=True, null=True)),
                ('benefits_medicine', models.TextField(blank=True, null=True)),
                ('side_effects_medicine', models.TextField(blank=True, null=True)),
                ('safety_advice_medicine', models.TextField(blank=True, null=True)),
                ('picture', models.FileField(null=True, upload_to='')),
                ('manufactured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manufacturer.manufacturer')),
            ],
        ),
    ]
