# Generated by Django 3.2.7 on 2021-09-17 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_alter_medicine_picture'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name_medicine']},
        ),
    ]
