# Generated by Django 3.2.7 on 2021-09-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_medicine_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='substitute',
            field=models.ManyToManyField(related_name='_medicine_medicine_substitute_+', to='medicine.Medicine'),
        ),
    ]
